// Mock data for FLOWLOG app

export const mockUser = {
  id: '1',
  name: 'Arjun',
  email: 'arjun@theprocess.com',
  role: 'Senior Developer',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
  streak: 12,
  flowPoints: 3420,
  flowPointsGoal: 500,
  level: 7,
  xp: 1850,
};

// ERP Work Orders with full details
export const mockWorkOrders = [
  {
    id: 'WO-2025-001',
    number: 'WO-2025-001',
    name: 'Mobile App Redesign',
    client: 'TechCorp Inc.',
    status: 'In Progress',
    priority: 'High',
    type: 'direct', // direct or sequence
    billable: true,
    rate: 950,
    currency: '₹',
    startDate: '2025-10-01',
    dueDate: '2025-11-15',
    estimatedHours: 120,
    actualHours: 45.5,
    billingPolicy: 'Per hour worked',
    description: 'Complete redesign of mobile application with new UI/UX',
    lastActivity: '2 hours ago',
  },
  {
    id: 'WO-2025-002',
    number: 'WO-2025-002',
    name: 'API Integration - Payment Gateway',
    client: 'StartupXYZ',
    status: 'In Progress',
    priority: 'High',
    type: 'direct',
    billable: true,
    rate: 1150,
    currency: '₹',
    startDate: '2025-10-10',
    dueDate: '2025-10-30',
    estimatedHours: 60,
    actualHours: 18.5,
    billingPolicy: 'Per project milestone',
    description: 'Integration of third-party payment gateway with existing system',
    lastActivity: '1 day ago',
  },
  {
    id: 'WO-2025-003',
    number: 'WO-2025-003',
    name: 'Database Migration Project',
    client: 'Enterprise Solutions Ltd.',
    status: 'In Progress',
    priority: 'Critical',
    type: 'sequence', // Process sequence type
    billable: true,
    rate: 1200,
    currency: '₹',
    startDate: '2025-10-05',
    dueDate: '2025-12-01',
    estimatedHours: 180,
    actualHours: 32,
    billingPolicy: 'Per step completion',
    description: 'Multi-phase database migration from legacy to cloud infrastructure',
    lastActivity: '3 days ago',
    processSteps: [
      { id: 'step-1', name: 'Assessment & Planning', status: 'Completed', hours: 12 },
      { id: 'step-2', name: 'Data Backup', status: 'Completed', hours: 8 },
      { id: 'step-3', name: 'Schema Migration', status: 'In Progress', hours: 12 },
      { id: 'step-4', name: 'Data Migration', status: 'Pending', hours: 0 },
      { id: 'step-5', name: 'Testing & Validation', status: 'Pending', hours: 0 },
    ],
  },
  {
    id: 'WO-2025-004',
    number: 'WO-2025-004',
    name: 'UI Component Library Development',
    client: 'Internal - The Process',
    status: 'In Progress',
    priority: 'Medium',
    type: 'direct',
    billable: false,
    rate: 0,
    currency: '₹',
    startDate: '2025-09-15',
    dueDate: '2025-11-30',
    estimatedHours: 200,
    actualHours: 87,
    billingPolicy: 'Internal project',
    description: 'Build reusable component library for all internal projects',
    lastActivity: '5 hours ago',
  },
  {
    id: 'WO-2025-005',
    number: 'WO-2025-005',
    name: 'E-commerce Platform Setup',
    client: 'RetailCo India',
    status: 'Not Started',
    priority: 'Medium',
    type: 'sequence',
    billable: true,
    rate: 1050,
    currency: '₹',
    startDate: '2025-11-01',
    dueDate: '2026-01-31',
    estimatedHours: 300,
    actualHours: 0,
    billingPolicy: 'Per milestone',
    description: 'Full e-commerce platform with inventory management',
    lastActivity: 'Not started',
    processSteps: [
      { id: 'step-1', name: 'Requirements Gathering', status: 'Pending', hours: 0 },
      { id: 'step-2', name: 'Platform Setup', status: 'Pending', hours: 0 },
      { id: 'step-3', name: 'Payment Integration', status: 'Pending', hours: 0 },
      { id: 'step-4', name: 'Inventory System', status: 'Pending', hours: 0 },
      { id: 'step-5', name: 'Testing & Launch', status: 'Pending', hours: 0 },
    ],
  },
  {
    id: 'WO-2025-006',
    number: 'WO-2025-006',
    name: 'Security Audit & Fixes',
    client: 'FinanceHub Corp',
    status: 'Pending',
    priority: 'Critical',
    type: 'direct',
    billable: true,
    rate: 1500,
    currency: '₹',
    startDate: '2025-10-25',
    dueDate: '2025-11-10',
    estimatedHours: 80,
    actualHours: 0,
    billingPolicy: 'Per hour worked',
    description: 'Comprehensive security audit and vulnerability fixes',
    lastActivity: 'Scheduled',
  },
];

export const mockTimeEntries = [
  // Oct 17 (Friday)
  {
    id: '1',
    task: 'Component Development',
    workOrderId: 'WO-2025-001',
    workOrderType: 'direct',
    startTime: '09:00',
    endTime: '11:30',
    duration: 150,
    category: 'Work',
    billable: true,
    rate: 950,
    amount: 2375,
    date: '2025-10-17',
    approved: true,
  },
  {
    id: '2',
    task: 'Team Standup',
    workOrderId: 'WO-2025-001',
    workOrderType: 'direct',
    startTime: '11:30',
    endTime: '12:00',
    duration: 30,
    category: 'Meeting',
    billable: false,
    rate: 0,
    amount: 0,
    date: '2025-10-17',
    approved: true,
  },
  {
    id: '3',
    task: 'Lunch Break',
    workOrderId: null,
    startTime: '12:00',
    endTime: '13:00',
    duration: 60,
    category: 'Lunch',
    billable: false,
    rate: 0,
    amount: 0,
    date: '2025-10-17',
    approved: true,
  },
  {
    id: '4',
    task: 'API Endpoint Testing',
    workOrderId: 'WO-2025-002',
    workOrderType: 'sequence',
    startTime: '13:00',
    endTime: '15:30',
    duration: 150,
    category: 'Work',
    billable: true,
    rate: 1150,
    amount: 2875,
    date: '2025-10-17',
    approved: false,
  },
  {
    id: '5',
    task: 'Code Review',
    workOrderId: 'WO-2025-004',
    workOrderType: 'direct',
    startTime: '15:30',
    endTime: '16:30',
    duration: 60,
    category: 'Work',
    billable: false,
    rate: 0,
    amount: 0,
    date: '2025-10-17',
    approved: false,
  },
  // Oct 16 (Thursday)
  {
    id: '6',
    task: 'Database Schema Design',
    workOrderId: 'WO-2025-003',
    workOrderType: 'sequence',
    startTime: '09:00',
    endTime: '12:00',
    duration: 180,
    category: 'Work',
    billable: true,
    rate: 1200,
    amount: 3600,
    date: '2025-10-16',
    approved: true,
  },
  {
    id: '7',
    task: 'Client Meeting',
    workOrderId: 'WO-2025-001',
    workOrderType: 'direct',
    startTime: '14:00',
    endTime: '15:30',
    duration: 90,
    category: 'Meeting',
    billable: false,
    rate: 0,
    amount: 0,
    date: '2025-10-16',
    approved: true,
  },
  // Oct 15 (Wednesday)
  {
    id: '8',
    task: 'Bug Fixes',
    workOrderId: 'WO-2025-002',
    workOrderType: 'sequence',
    startTime: '10:00',
    endTime: '13:00',
    duration: 180,
    category: 'Work',
    billable: true,
    rate: 1150,
    amount: 3450,
    date: '2025-10-15',
    approved: true,
  },
  {
    id: '9',
    task: 'Documentation',
    workOrderId: 'WO-2025-004',
    workOrderType: 'direct',
    startTime: '14:00',
    endTime: '16:00',
    duration: 120,
    category: 'Work',
    billable: false,
    rate: 0,
    amount: 0,
    date: '2025-10-15',
    approved: true,
  },
  // Oct 14 (Tuesday)
  {
    id: '10',
    task: 'Sprint Planning',
    workOrderId: null,
    startTime: '09:30',
    endTime: '11:00',
    duration: 90,
    category: 'Meeting',
    billable: false,
    rate: 0,
    amount: 0,
    date: '2025-10-14',
    approved: true,
  },
  {
    id: '11',
    task: 'Feature Implementation',
    workOrderId: 'WO-2025-001',
    workOrderType: 'direct',
    startTime: '11:00',
    endTime: '16:00',
    duration: 300,
    category: 'Work',
    billable: true,
    rate: 950,
    amount: 4750,
    date: '2025-10-14',
    approved: true,
  },
  // Oct 13 (Monday)
  {
    id: '12',
    task: 'Weekly Sync',
    workOrderId: null,
    startTime: '09:00',
    endTime: '10:00',
    duration: 60,
    category: 'Meeting',
    billable: false,
    rate: 0,
    amount: 0,
    date: '2025-10-13',
    approved: true,
  },
  {
    id: '13',
    task: 'UI Component Library',
    workOrderId: 'WO-2025-004',
    workOrderType: 'direct',
    startTime: '10:30',
    endTime: '15:00',
    duration: 270,
    category: 'Work',
    billable: false,
    rate: 0,
    amount: 0,
    date: '2025-10-13',
    approved: true,
  },
];

export const mockProcessHierarchy = [
  {
    id: 'mp-1',
    name: 'Software Development',
    type: 'main',
    children: [
      {
        id: 'kp-1',
        name: 'Frontend Development',
        type: 'key',
        children: [
          {
            id: 'p-1',
            name: 'Component Building',
            type: 'process',
            children: [
              { id: 's-1', name: 'Design Review', type: 'step' },
              { id: 's-2', name: 'Implementation', type: 'step' },
              { id: 's-3', name: 'Testing', type: 'step' },
            ],
          },
          {
            id: 'p-2',
            name: 'State Management',
            type: 'process',
            children: [
              { id: 's-4', name: 'Architecture Planning', type: 'step' },
              { id: 's-5', name: 'Implementation', type: 'step' },
            ],
          },
        ],
      },
      {
        id: 'kp-2',
        name: 'Backend Development',
        type: 'key',
        children: [
          {
            id: 'p-3',
            name: 'API Development',
            type: 'process',
            children: [
              { id: 's-6', name: 'Endpoint Design', type: 'step' },
              { id: 's-7', name: 'Implementation', type: 'step' },
              { id: 's-8', name: 'Documentation', type: 'step' },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'mp-2',
    name: 'Project Management',
    type: 'main',
    children: [
      {
        id: 'kp-3',
        name: 'Planning',
        type: 'key',
        children: [
          {
            id: 'p-4',
            name: 'Sprint Planning',
            type: 'process',
            children: [
              { id: 's-9', name: 'Backlog Review', type: 'step' },
              { id: 's-10', name: 'Task Estimation', type: 'step' },
            ],
          },
        ],
      },
    ],
  },
];

export const mockWeeklyData = [
  { day: 'Mon', hours: 7.5, focus: 6.2 },
  { day: 'Tue', hours: 8.0, focus: 7.1 },
  { day: 'Wed', hours: 6.5, focus: 5.8 },
  { day: 'Thu', hours: 8.5, focus: 7.8 },
  { day: 'Fri', hours: 7.0, focus: 6.5 },
  { day: 'Sat', hours: 0, focus: 0 },
  { day: 'Sun', hours: 0, focus: 0 },
];

export const mockProjectBreakdown = [
  { name: 'Mobile App Redesign', hours: 18, color: '#4B5CFB' },
  { name: 'API Integration', hours: 12, color: '#00C7B7' },
  { name: 'UI Component Library', hours: 8, color: '#F0BB00' },
  { name: 'Database Migration', hours: 5, color: '#FF4D4D' },
];

export const mockBadges = [
  {
    id: 'streak-7',
    name: '7 Day Streak',
    icon: 'flame',
    earned: true,
    date: '2025-10-15',
  },
  {
    id: 'focus-master',
    name: 'Focus Master',
    description: '10 hours of deep work in one week',
    icon: 'target',
    earned: true,
    date: '2025-10-12',
  },
  {
    id: 'early-bird',
    name: 'Early Bird',
    description: 'Started work before 8 AM for 5 days',
    icon: 'sunrise',
    earned: false,
  },
  {
    id: 'century',
    name: 'Century Club',
    description: 'Logged 100 hours',
    icon: 'trophy',
    earned: true,
    date: '2025-10-01',
  },
];

export const mockTeamMembers = [
  {
    id: '1',
    name: 'Sarah Johnson',
    role: 'Frontend Developer',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    hoursThisWeek: 38.5,
    status: 'approved',
  },
  {
    id: '2',
    name: 'Michael Chen',
    role: 'Backend Developer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    hoursThisWeek: 42.0,
    status: 'pending',
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    role: 'UI/UX Designer',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    hoursThisWeek: 35.5,
    status: 'approved',
  },
];

export const categories = [
  { id: 'work', name: 'Work', color: '#4B5CFB' },
  { id: 'meeting', name: 'Meeting', color: '#00C7B7' },
  { id: 'lunch', name: 'Lunch', color: '#F0BB00' },
  { id: 'break', name: 'Break', color: '#FF4D4D' },
  { id: 'travel', name: 'Travel', color: '#00D68F' },
];

// Quick activity types (non-work-order activities)
export const quickActivities = [
  {
    id: 'lunch',
    name: 'Lunch Break',
    icon: 'utensils',
    color: '#F0BB00',
    description: 'Take a lunch break',
    billable: false,
  },
  {
    id: 'meeting',
    name: 'Meeting',
    icon: 'users',
    color: '#00C7B7',
    description: 'Team meeting or discussion',
    billable: false,
  },
  {
    id: 'discussion',
    name: 'Discussion',
    icon: 'message-circle',
    color: '#4B5CFB',
    description: 'Quick discussion or sync',
    billable: false,
  },
  {
    id: 'outpass',
    name: 'Outpass',
    icon: 'door-open',
    color: '#FF4D4D',
    description: 'Out of office',
    billable: false,
  },
  {
    id: 'other',
    name: 'Other',
    icon: 'edit',
    color: '#8B5CF6',
    description: 'Other activity (specify reason)',
    billable: false,
  },
];

// Other activities (Lunch, Meeting, etc.) - formatted for Work Order Selector
export const mockOtherActivities = [
  {
    id: 'OTHER-001',
    number: 'Lunch',
    name: 'Lunch Break',
    client: 'Personal',
    status: 'Available',
    priority: 'Normal',
    type: 'others',
    billable: false,
    rate: 0,
    currency: '₹',
    description: 'Take a lunch break',
    lastActivity: 'Always available',
  },
  {
    id: 'OTHER-002',
    number: 'Meetings',
    name: 'Team Meetings',
    client: 'Internal',
    status: 'Available',
    priority: 'Normal',
    type: 'others',
    billable: false,
    rate: 0,
    currency: '₹',
    description: 'Team meetings, standups, or sync calls',
    lastActivity: 'Always available',
  },
  {
    id: 'OTHER-003',
    number: 'Discussion',
    name: 'Discussion / Sync',
    client: 'Internal',
    status: 'Available',
    priority: 'Normal',
    type: 'others',
    billable: false,
    rate: 0,
    currency: '₹',
    description: 'Quick discussions or one-on-ones',
    lastActivity: 'Always available',
  },
  {
    id: 'OTHER-004',
    number: 'Outpass',
    name: 'Out of Office',
    client: 'Personal',
    status: 'Available',
    priority: 'Normal',
    type: 'others',
    billable: false,
    rate: 0,
    currency: '₹',
    description: 'Out of office or personal leave',
    lastActivity: 'Always available',
  },
  {
    id: 'OTHER-005',
    number: 'Others',
    name: 'Other Activities',
    client: 'General',
    status: 'Available',
    priority: 'Normal',
    type: 'others',
    billable: false,
    rate: 0,
    currency: '₹',
    description: 'Any other miscellaneous activity',
    lastActivity: 'Always available',
  },
];

// Calendar-specific data for Flow Calendar module
export const mockCalendarEntries = [
  // Oct 23 (Today - Thursday)
  {
    id: 'cal-1',
    task: 'Deep Work Session',
    workOrderId: 'WO-2025-001',
    startTime: '09:00',
    endTime: '11:30',
    duration: 150,
    category: 'work',
    billable: true,
    date: '2025-10-23',
    flowScore: 92,
    mood: '😃',
    planned: true,
    actual: true,
  },
  {
    id: 'cal-2',
    task: 'Team Standup',
    workOrderId: null,
    startTime: '11:30',
    endTime: '12:00',
    duration: 30,
    category: 'meeting',
    billable: false,
    date: '2025-10-23',
    flowScore: 65,
    mood: '😃',
    planned: true,
    actual: true,
  },
  {
    id: 'cal-3',
    task: 'Lunch Break',
    workOrderId: null,
    startTime: '12:00',
    endTime: '13:00',
    duration: 60,
    category: 'lunch',
    billable: false,
    date: '2025-10-23',
    flowScore: 0,
    mood: '😐',
    planned: true,
    actual: true,
  },
  {
    id: 'cal-4',
    task: 'Code Review & Debugging',
    workOrderId: 'WO-2025-002',
    startTime: '13:00',
    endTime: '15:30',
    duration: 150,
    category: 'work',
    billable: true,
    date: '2025-10-23',
    flowScore: 88,
    mood: '😃',
    planned: true,
    actual: true,
  },
  {
    id: 'cal-5',
    task: 'Client Presentation',
    workOrderId: 'WO-2025-001',
    startTime: '15:30',
    endTime: '16:30',
    duration: 60,
    category: 'meeting',
    billable: false,
    date: '2025-10-23',
    flowScore: 78,
    mood: '😐',
    planned: true,
    actual: false, // Planned but not logged yet
  },
  // Oct 22 (Yesterday - Wednesday)
  {
    id: 'cal-6',
    task: 'Feature Development',
    workOrderId: 'WO-2025-004',
    startTime: '09:30',
    endTime: '12:00',
    duration: 150,
    category: 'work',
    billable: true,
    date: '2025-10-22',
    flowScore: 95,
    mood: '😃',
    planned: true,
    actual: true,
  },
  {
    id: 'cal-7',
    task: 'Architecture Review',
    workOrderId: 'WO-2025-003',
    startTime: '14:00',
    endTime: '16:00',
    duration: 120,
    category: 'work',
    billable: true,
    date: '2025-10-22',
    flowScore: 85,
    mood: '😃',
    planned: true,
    actual: true,
  },
  // Oct 21 (Tuesday)
  {
    id: 'cal-8',
    task: 'Sprint Planning',
    workOrderId: null,
    startTime: '09:00',
    endTime: '11:00',
    duration: 120,
    category: 'meeting',
    billable: false,
    date: '2025-10-21',
    flowScore: 70,
    mood: '😐',
    planned: true,
    actual: true,
  },
  {
    id: 'cal-9',
    task: 'API Development',
    workOrderId: 'WO-2025-002',
    startTime: '11:00',
    endTime: '15:00',
    duration: 240,
    category: 'work',
    billable: true,
    date: '2025-10-21',
    flowScore: 90,
    mood: '😃',
    planned: true,
    actual: true,
  },
];

// Daily flow scores for heatmap (last 30 days)
export const mockDailyFlowScores = [
  { date: '2025-09-24', score: 78 },
  { date: '2025-09-25', score: 82 },
  { date: '2025-09-26', score: 75 },
  { date: '2025-09-27', score: 88 },
  { date: '2025-09-28', score: 0 }, // Weekend
  { date: '2025-09-29', score: 0 }, // Weekend
  { date: '2025-09-30', score: 85 },
  { date: '2025-10-01', score: 90 },
  { date: '2025-10-02', score: 87 },
  { date: '2025-10-03', score: 92 },
  { date: '2025-10-04', score: 84 },
  { date: '2025-10-05', score: 0 }, // Weekend
  { date: '2025-10-06', score: 0 }, // Weekend
  { date: '2025-10-07', score: 88 },
  { date: '2025-10-08', score: 91 },
  { date: '2025-10-09', score: 86 },
  { date: '2025-10-10', score: 89 },
  { date: '2025-10-11', score: 93 },
  { date: '2025-10-12', score: 0 }, // Weekend
  { date: '2025-10-13', score: 0 }, // Weekend
  { date: '2025-10-14', score: 87 },
  { date: '2025-10-15', score: 90 },
  { date: '2025-10-16', score: 85 },
  { date: '2025-10-17', score: 88 },
  { date: '2025-10-18', score: 92 },
  { date: '2025-10-19', score: 0 }, // Weekend
  { date: '2025-10-20', score: 0 }, // Weekend
  { date: '2025-10-21', score: 90 },
  { date: '2025-10-22', score: 95 },
  { date: '2025-10-23', score: 82 },
];

// AI insights and tips
export const mockAIInsights = [
  {
    id: 'insight-1',
    title: 'Peak Focus Window',
    description: 'Your best focus happens between 09:30–11:00. Schedule deep work here.',
    type: 'productivity',
    icon: 'zap',
  },
  {
    id: 'insight-2',
    title: 'Meeting Fatigue',
    description: 'You have 3+ meetings tomorrow. Consider blocking 2h for focused work.',
    type: 'warning',
    icon: 'alert-triangle',
  },
  {
    id: 'insight-3',
    title: 'Flow Streak',
    description: '5 days with Flow Score > 85. Keep the momentum going!',
    type: 'achievement',
    icon: 'trending-up',
  },
  {
    id: 'insight-4',
    title: 'Break Pattern',
    description: 'Taking breaks every 90 mins increases your Flow Score by 12%.',
    type: 'tip',
    icon: 'coffee',
  },
];

// Billing data for Cost Sheet
export const mockClientBilling = [
  {
    id: 'client-1',
    client: 'TechCorp Inc.',
    workOrderId: 'WO-2025-001',
    billableHours: 15.5,
    amount: 14725,
    status: 'Approved',
    lastUpdated: '2025-10-17',
  },
  {
    id: 'client-2',
    client: 'StartupXYZ',
    workOrderId: 'WO-2025-002',
    billableHours: 8.5,
    amount: 9775,
    status: 'Pending',
    lastUpdated: '2025-10-17',
  },
  {
    id: 'client-3',
    client: 'Enterprise Solutions Ltd.',
    workOrderId: 'WO-2025-003',
    billableHours: 3.0,
    amount: 3600,
    status: 'Approved',
    lastUpdated: '2025-10-16',
  },
];

// Billing trend data (last 7 days)
export const mockBillingTrend = [
  { day: 'Mon', amount: 4750 },
  { day: 'Tue', amount: 0 },
  { day: 'Wed', amount: 2550 },
  { day: 'Thu', amount: 3600 },
  { day: 'Fri', amount: 4500 },
  { day: 'Sat', amount: 0 },
  { day: 'Sun', amount: 0 },
];

// Recent "Others" activity entries (includes Work Orders and Others)
export const mockRecentOthersActivities = [
  // Today - Oct 25
  {
    id: 'recent-1',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'UI/UX improvements for dashboard',
    date: '2025-10-25',
    duration: 125,
    durationMinutes: 125,
    startTime: '09:15',
    endTime: '11:20',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 1200,
  },
  {
    id: 'recent-2',
    activityId: 'OTHER-001',
    activityName: 'Lunch',
    description: 'Team lunch at cafeteria',
    date: '2025-10-25',
    duration: 45,
    durationMinutes: 45,
    startTime: '13:00',
    endTime: '13:45',
    category: 'Lunch',
  },
  {
    id: 'recent-3',
    activityId: 'WO-2025-003',
    activityName: 'WO-2025-003',
    description: 'Payment gateway integration testing',
    date: '2025-10-25',
    duration: 95,
    durationMinutes: 95,
    startTime: '14:00',
    endTime: '15:35',
    category: 'Work',
    workOrderType: 'sequence',
    billable: true,
    rate: 1200,
  },
  // Yesterday - Oct 24
  {
    id: 'recent-4',
    activityId: 'WO-2025-002',
    activityName: 'WO-2025-002',
    description: 'Inventory module enhancements',
    date: '2025-10-24',
    duration: 180,
    durationMinutes: 180,
    startTime: '09:00',
    endTime: '12:00',
    category: 'Work',
    workOrderType: 'sequence',
    billable: true,
    rate: 1150,
  },
  {
    id: 'recent-5',
    activityId: 'OTHER-002',
    activityName: 'Meetings',
    description: 'Daily standup with team',
    date: '2025-10-24',
    duration: 15,
    durationMinutes: 15,
    startTime: '10:30',
    endTime: '10:45',
    category: 'Meeting',
  },
  {
    id: 'recent-6',
    activityId: 'WO-2025-004',
    activityName: 'WO-2025-004',
    description: 'Documentation updates',
    date: '2025-10-24',
    duration: 60,
    durationMinutes: 60,
    startTime: '15:30',
    endTime: '16:30',
    category: 'Work',
    workOrderType: 'direct',
    billable: false,
    rate: 0,
  },
  // Oct 23
  {
    id: 'recent-7',
    activityId: 'OTHER-001',
    activityName: 'Lunch',
    description: 'Lunch break',
    date: '2025-10-23',
    duration: 60,
    durationMinutes: 60,
    startTime: '13:00',
    endTime: '14:00',
    category: 'Lunch',
  },
  {
    id: 'recent-8',
    activityId: 'OTHER-003',
    activityName: 'Discussion',
    description: 'Code review discussion with Sarah',
    date: '2025-10-23',
    duration: 30,
    durationMinutes: 30,
    startTime: '11:15',
    endTime: '11:45',
    category: 'Discussion',
  },
  {
    id: 'recent-9',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'Mobile responsive fixes',
    date: '2025-10-23',
    duration: 140,
    durationMinutes: 140,
    startTime: '09:00',
    endTime: '11:20',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 1200,
  },
  // Oct 22
  {
    id: 'recent-10',
    activityId: 'OTHER-002',
    activityName: 'Meetings',
    description: 'Sprint planning meeting',
    date: '2025-10-22',
    duration: 90,
    durationMinutes: 90,
    startTime: '10:00',
    endTime: '11:30',
    category: 'Meeting',
  },
  {
    id: 'recent-11',
    activityId: 'WO-2025-003',
    activityName: 'WO-2025-003',
    description: 'API integration for payment module',
    date: '2025-10-22',
    duration: 210,
    durationMinutes: 210,
    startTime: '09:00',
    endTime: '12:30',
    category: 'Work',
    workOrderType: 'sequence',
    billable: true,
    rate: 1200,
  },
  {
    id: 'recent-12',
    activityId: 'OTHER-001',
    activityName: 'Lunch',
    description: 'Lunch break',
    date: '2025-10-22',
    duration: 60,
    durationMinutes: 60,
    startTime: '13:00',
    endTime: '14:00',
    category: 'Lunch',
  },
  // Oct 21
  {
    id: 'recent-13',
    activityId: 'OTHER-004',
    activityName: 'Outpass',
    description: 'Bank work',
    date: '2025-10-21',
    duration: 120,
    durationMinutes: 120,
    startTime: '14:00',
    endTime: '16:00',
    category: 'Outpass',
  },
  {
    id: 'recent-14',
    activityId: 'WO-2025-002',
    activityName: 'WO-2025-002',
    description: 'Bug fixes in inventory system',
    date: '2025-10-21',
    duration: 165,
    durationMinutes: 165,
    startTime: '09:30',
    endTime: '12:15',
    category: 'Work',
    workOrderType: 'sequence',
    billable: true,
    rate: 1150,
  },
  {
    id: 'recent-15',
    activityId: 'OTHER-003',
    activityName: 'Discussion',
    description: 'Quick sync with manager',
    date: '2025-10-21',
    duration: 20,
    durationMinutes: 20,
    startTime: '16:30',
    endTime: '16:50',
    category: 'Discussion',
  },
  // Oct 20 - Adding more entries for better activity history
  {
    id: 'recent-16',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'Implementing new navigation flow',
    date: '2025-10-20',
    duration: 155,
    durationMinutes: 155,
    startTime: '09:00',
    endTime: '11:35',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 1200,
  },
  {
    id: 'recent-17',
    activityId: 'WO-2025-003',
    activityName: 'WO-2025-003',
    description: 'Database schema updates for payment module',
    date: '2025-10-20',
    duration: 180,
    durationMinutes: 180,
    startTime: '13:00',
    endTime: '16:00',
    category: 'Work',
    workOrderType: 'sequence',
    billable: true,
    rate: 1200,
  },
  // Oct 19
  {
    id: 'recent-18',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'Component refactoring and optimization',
    date: '2025-10-19',
    duration: 105,
    durationMinutes: 105,
    startTime: '14:00',
    endTime: '15:45',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 1200,
  },
  {
    id: 'recent-19',
    activityId: 'WO-2025-002',
    activityName: 'WO-2025-002',
    description: 'Code review and testing',
    date: '2025-10-19',
    duration: 120,
    durationMinutes: 120,
    startTime: '10:00',
    endTime: '12:00',
    category: 'Work',
    workOrderType: 'sequence',
    billable: true,
    rate: 1150,
  },
  // Oct 18
  {
    id: 'recent-20',
    activityId: 'WO-2025-003',
    activityName: 'WO-2025-003',
    description: 'Payment API integration',
    date: '2025-10-18',
    duration: 195,
    durationMinutes: 195,
    startTime: '09:15',
    endTime: '12:30',
    category: 'Work',
    workOrderType: 'sequence',
    billable: true,
    rate: 1200,
  },
  {
    id: 'recent-21',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'Design implementation for mobile screens',
    date: '2025-10-18',
    duration: 165,
    durationMinutes: 165,
    startTime: '13:30',
    endTime: '16:15',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 1200,
  },
  // Oct 17
  {
    id: 'recent-22',
    activityId: 'WO-2025-002',
    activityName: 'WO-2025-002',
    description: 'Performance optimization',
    date: '2025-10-17',
    duration: 135,
    durationMinutes: 135,
    startTime: '09:00',
    endTime: '11:15',
    category: 'Work',
    workOrderType: 'sequence',
    billable: true,
    rate: 1150,
  },
  {
    id: 'recent-23',
    activityId: 'WO-2025-003',
    activityName: 'WO-2025-003',
    description: 'Security audit and updates',
    date: '2025-10-17',
    duration: 150,
    durationMinutes: 150,
    startTime: '13:00',
    endTime: '15:30',
    category: 'Work',
    workOrderType: 'sequence',
    billable: true,
    rate: 1200,
  },
  // Oct 16
  {
    id: 'recent-24',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'User feedback implementation',
    date: '2025-10-16',
    duration: 115,
    durationMinutes: 115,
    startTime: '10:00',
    endTime: '11:55',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 1200,
  },
];

// Reports Module Mock Data
export const mockReportsData = {
  // Last ERP sync time
  lastSync: '12:42',
  
  // Work Orders (Direct) Summary
  workOrdersDirect: {
    totalHours: 45.5,
    billableHours: 38.5,
    avgRate: 1033,
    totalAmount: 39770.5,
    entries: [
      {
        id: 'WO-2025-001',
        name: 'Mobile App Redesign',
        client: 'TechCorp Inc.',
        hours: 24.5,
        billableHours: 24.5,
        rate: 950,
        amount: 23275,
        approved: true,
      },
      {
        id: 'WO-2025-002',
        name: 'API Integration',
        client: 'StartupXYZ',
        hours: 14.0,
        billableHours: 14.0,
        rate: 1150,
        amount: 16100,
        approved: true,
      },
      {
        id: 'WO-2025-004',
        name: 'UI Component Library',
        client: 'Internal',
        hours: 7.0,
        billableHours: 0,
        rate: 0,
        amount: 0,
        approved: true,
      },
    ],
    missingRateCount: 0,
  },
  
  // Process-Sequence Work Orders Summary
  workOrdersSequence: {
    totalHours: 32.0,
    billableHours: 32.0,
    avgRate: 1200,
    totalAmount: 38400,
    entries: [
      {
        id: 'WO-2025-003',
        name: 'Database Migration',
        client: 'Enterprise Solutions Ltd.',
        hours: 32.0,
        billableHours: 32.0,
        rate: 1200,
        amount: 38400,
        approved: true,
        hierarchy: {
          main: 'Infrastructure',
          key: 'Database Services',
          process: 'Migration',
          steps: [
            { name: 'Assessment & Planning', hours: 12.0, rate: 1200, amount: 14400, approved: true },
            { name: 'Data Backup', hours: 8.0, rate: 1200, amount: 9600, approved: true },
            { name: 'Schema Migration', hours: 12.0, rate: 1200, amount: 14400, approved: true },
          ],
        },
      },
    ],
    missingRateCount: 0,
  },
  
  // General Activities Summary
  generalActivities: {
    totalHours: 12.5,
    billableHours: 0,
    entries: [
      { category: 'Meeting', hours: 4.5, color: '#00C7B7' },
      { category: 'Lunch', hours: 5.0, color: '#F0BB00' },
      { category: 'Break', hours: 2.0, color: '#FF8A00' },
      { category: 'Discussion', hours: 1.0, color: '#8B5CF6' },
    ],
  },
  
  // Totals
  totals: {
    totalLoggedHours: 90.0,
    totalBillableHours: 70.5,
    totalNonBillableHours: 19.5,
    totalBillableAmount: 78170.5,
  },
  
  // Integrity flags
  hasMultiCurrency: false,
  missingRateEntries: [],
  pendingApprovalHours: 2.5,
};
